Time, LogLevel, Message
2021_10_13_18_50_20,Information,"Task: Reload task of test"
2021_10_13_18_50_20,Information,"Proxy: https://localhost"
2021_10_13_18_50_20,Information,"Wait: 31 seconds"
2021_10_13_18_50_20,Information,"Poll: 15 seconds"
2021_10_13_18_50_20,Information,"Log: C:\Users\qmi\Source\Repos\QlikSenseTask\QlikSenseTaskSource-3.X\QlikSenseTask\bin\Release"
2021_10_13_18_50_20,Information,"Delete Log: -90 days"
2021_10_13_18_50_20,Information,"Creating connection..."
2021_10_13_18_50_20,Debug,"Creating web connection..."
2021_10_13_18_50_20,Debug,"Creating CookierAwareWebClient..."
2021_10_13_18_50_20,Debug,"calling /qrs/about"
2021_10_13_18_50_20,Debug,"setting headers"
2021_10_13_18_50_20,Debug,"constructing query string"
2021_10_13_18_50_20,Debug,"calling https://localhost/qrs/about"
2021_10_13_18_50_20,Debug,"error: The underlying connection was closed: An unexpected error occurred on a send."
2021_10_13_18_50_21,Error,"System.Exception: Couldnt connect to the server at https://localhost , check that the Proxy and QRS are running.  Message: Object reference not set to an instance of an object.
   at QVnextDemoBuilder.QRSNTLMWebClient..ctor(String QRSserverURL, Int32 requesttimeout, Logger logger) in C:\Users\qmi\Source\Repos\QlikSenseTask\QlikSenseTaskSource-3.X\QlikSenseTask\QRSNTLMWebClient.cs:line 44
   at QlikSenseJSONObjects.QlikSenseJSONHelper..ctor(String url, Int32 timeout, Logger logger) in C:\Users\qmi\Source\Repos\QlikSenseTask\QlikSenseTaskSource-3.X\QlikSenseTask\QlikSenseJSONHelper.cs:line 27
   at QlikSenseTask.Program.Main(String[] args) in C:\Users\qmi\Source\Repos\QlikSenseTask\QlikSenseTaskSource-3.X\QlikSenseTask\Program.cs:line 160"
2021_10_13_18_50_21,Information,"Returning Errorlevel 8"
